apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: "nginx"
  rules:
  - host: {{ .Values.Ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Release.Name }}
            port: 
              number: {{ .Values.Service.servicePort }}
      - path: /v2
        pathType: Prefix
        backend:
          service:
            name: hello-world2
            port:
              number: {{ .Values.Service.servicePort }}
  tls:
    - hosts:
      - web04.go4clouds.net
      secretName: web-go4clouds-net-tls
