apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP
status:
  loadBalancer: {}
