apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.Service.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.Service.appPort }}
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP
status:
  loadBalancer: {}
