apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: gitmyapp-kubernetes
    meta.helm.sh/release-namespace: myapp
spec:
  strategy: {} 
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: ghcr.io/tuduce/myapp:v0.6
        name: myapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
              path: /
              port: http
          failureThreshold: 1
          initialDelaySeconds: 3
          periodSeconds: 5

