apiVersion: v1
kind: Service
metadata:
  namespace: myapp
  name: myapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
  type: ClusterIP
status:
  loadBalancer: {}
