apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: myapp
spec:
  containers:
  - name: myapp
    image: ghcr.io/tuduce/myapp:v0.6
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
    livenessProbe:
      httpGet:
          path: /
          port: http
      failureThreshold: 1
      initialDelaySeconds: 3
      periodSeconds: 5
